name: Yes we can

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Download latest version of Cascadia 
      run: | 
        curl -L https://github.com/microsoft/cascadia-code/releases/latest/download/Cascadia.ttf  --output Cascadia.ttf
    - name: Install FontForge
      run: |
        sudo add-apt-repository ppa:fontforge/fontforge -y -u;
        sudo apt-get install fontforge -y;
    - name: Download Font Patcher
      run: curl -L https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/font-patcher --output font-patcher 
    - name: Make a directory for source fonts
      run: mkdir -p src/glyphs
    - name: Install PIP
      run: sudo apt install python-pip -y
    - name: Install config
      run: pip install configparser
